import React from 'react'
import { generateReportId } from '../utils/reportDataAdapters'

// A4 Dimensions at 96dpi (794 x 1123)
const A4_WIDTH = 794
const A4_HEIGHT = 1123

export default function PdfPageFrame({
  children,
  pageNumber,
  totalPages,
  reportData
}) {
  const generatedDate = new Date(reportData.created_at || Date.now()).toLocaleDateString()
  const reportId = generateReportId(reportData.pr_url, reportData.created_at)

  return (
    <div
      style={{
        width: `${A4_WIDTH}px`,
        height: `${A4_HEIGHT}px`,
        position: 'relative',
        backgroundColor: '#ffffff',
        color: '#0f172a', // slate-900
        fontFamily: '"Inter", sans-serif',
        display: 'flex',
        flexDirection: 'column',
        boxSizing: 'border-box',
        padding: '40px',
        overflow: 'hidden',
      }}
      className="pdf-page-frame"
    >
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
        {children}
      </div>

      {/* Consistent Footer */}
      <div
        style={{
          marginTop: 'auto',
          borderTop: '1px solid #e2e8f0', // slate-200
          paddingTop: '16px',
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          fontSize: '10px',
          color: '#64748b', // slate-500
        }}
      >
        <div>Generated by PRism · Confidential · {reportId} · {generatedDate}</div>
        <div>Page {pageNumber} of {totalPages}</div>
      </div>
    </div>
  )
}
